# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time', 'name']},
        ),
    ]
